server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:file:./tentFactoryTestDb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: tentFactory-admin
      password: backpacker
    realmImportFile: baeldung-realm.json
